stages:
  - check
  - build
  - test
  - deploy
  - cleanup

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_TAG: "1.0"

before_script:
  # Ensure Docker is installed before logging in
  - sudo apt-get update
  - sudo apt-get install -y docker.io docker-compose
  - sudo docker --version
  - sudo docker-compose --version
  - echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USER" --password-stdin

check:
  stage: check
  script:
    # You can retain the version checks here for verification
    - sudo docker --version
    - sudo docker-compose --version
  only:
    - staging
    - main

build:
  stage: build
  script:
    - sudo docker-compose -f deploy/docker-compose.yml build
  only:
    - staging
    - main

test:
  stage: test
  script:
    
    - sudo docker-compose -f deploy/docker-compose.yml run --rm idh_container /bin/sh -c "export PYTHONPATH=/usr/src/app:\$PYTHONPATH && pytest tests/"
  only:
    - staging
  tags:
    - test

deploy:
  stage: deploy
  script:
    - sudo docker-compose -f deploy/docker-compose.yml up -d
    - sudo docker tag inventorydatahub contactjawwad/idh-app:idh-$DOCKER_IMAGE_TAG
    - sudo docker tag inventorydatahub contactjawwad/idh-app:idh-latest
    - sudo docker tag my-nginx-image contactjawwad/idh-app:nginx-$DOCKER_IMAGE_TAG
    - sudo docker tag my-nginx-image contactjawwad/idh-app:nginx-latest
    - sudo docker push contactjawwad/idh-app:idh-$DOCKER_IMAGE_TAG
    - sudo docker push contactjawwad/idh-app:idh-latest
    - sudo docker push contactjawwad/idh-app:nginx-$DOCKER_IMAGE_TAG
    - sudo docker push contactjawwad/idh-app:nginx-latest
  only:
    - main
  tags:
    - deploy

cleanup_app:
  stage: cleanup
  script:
    # Stop and remove all Docker containers
    - sudo docker-compose -f deploy/docker-compose.yml down --rmi all
    # Remove all Docker images
    - sudo docker image prune -af
    # Optionally remove Docker volumes (uncomment if needed)
    # - docker volume prune -f
    # Remove any dangling images
    - sudo docker system prune -af
  when: manual
  only:
    - main
  tags:
    - cleanup
