version: '3.8'
services:
  idh_container:
    image: inventorydatahub  # The Docker image for the IDH container
    build:
      context: .. # The Docker image for the IDH container
      dockerfile: deploy/idh-docker/Dockerfile
      args:
        - CACHEBUST=1  # Use this to bust cache intentionally when needed
    volumes:
      - idh_logs:/var/log/IDHLogs
    networks:
      - myappnetwork
    deploy:
      resources:
        limits:
          memory: 8g
          cpus: '4.0'

  nginx_container:
    image: my-nginx-image   # The Docker image for the Nginx container
    build:
      context: ..
      dockerfile: deploy/nginx-docker/Dockerfile
      args:
        - CACHEBUST=1  # Use this to bust cache intentionally when needed
    ports:
      - "80:80"
    depends_on:
      - idh_container
    volumes:
      - nginx_logs:/var/log/nginx
    networks:
      - myappnetwork
    deploy:
      resources:
        limits:
          memory: 8g
          cpus: '4.0'

networks:
  myappnetwork:
    driver: bridge

volumes:
  idh_logs:
  nginx_logs:
